// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecetasRedondas.Models;

#nullable disable

namespace RecetasRedondas.Data.Migrations
{
    [DbContext(typeof(RecetasRedondasAppContext))]
    partial class RecetasRedondasAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecetasRedondas.Models.Alergeno", b =>
                {
                    b.Property<int>("IdAlergeno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlergeno"));

                    b.Property<int>("IdIngrediente")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientesIdIngrediente")
                        .HasColumnType("int");

                    b.Property<int?>("UsuariosIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdAlergeno");

                    b.HasIndex("IngredientesIdIngrediente");

                    b.HasIndex("UsuariosIdUsuario");

                    b.ToTable("Alergenos");
                });

            modelBuilder.Entity("RecetasRedondas.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Especial")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PuntuacionPromedio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Descripcion = "Platos deliciosos de carne",
                            Especial = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3125),
                            Icono = "https://ik.imagekit.io/Mariocanizares/carne.webp?updatedAt=1726218723472",
                            NombreCategoria = "Carnes",
                            PuntuacionPromedio = 4.5m
                        },
                        new
                        {
                            IdCategoria = 2,
                            Descripcion = "Platos variados con arroz",
                            Especial = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3198),
                            Icono = "https://ik.imagekit.io/Mariocanizares/arroz.png?updatedAt=1726218452623",
                            NombreCategoria = "Arroces",
                            PuntuacionPromedio = 4.8m
                        },
                        new
                        {
                            IdCategoria = 3,
                            Descripcion = "Guisos tradicionales y caseros",
                            Especial = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3202),
                            Icono = "https://ik.imagekit.io/Mariocanizares/guisos.png?updatedAt=1726218800757",
                            NombreCategoria = "Guisos",
                            PuntuacionPromedio = 4.7m
                        },
                        new
                        {
                            IdCategoria = 4,
                            Descripcion = "Platos exquisitos de mariscos",
                            Especial = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3205),
                            Icono = "https://ik.imagekit.io/Mariocanizares/marisco.webp?updatedAt=1726218800789",
                            NombreCategoria = "Mariscos",
                            PuntuacionPromedio = 4.6m
                        },
                        new
                        {
                            IdCategoria = 5,
                            Descripcion = "Platos frescos de pescados",
                            Especial = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3209),
                            Icono = "https://ik.imagekit.io/Mariocanizares/pescado.png?updatedAt=1726218801946",
                            NombreCategoria = "Pescados",
                            PuntuacionPromedio = 4.7m
                        },
                        new
                        {
                            IdCategoria = 6,
                            Descripcion = "Platos deliciosos de pasta",
                            Especial = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3212),
                            Icono = "https://ik.imagekit.io/Mariocanizares/pasta.png?updatedAt=1726218800772",
                            NombreCategoria = "Pastas",
                            PuntuacionPromedio = 4.5m
                        },
                        new
                        {
                            IdCategoria = 7,
                            Descripcion = "Frescas y saludables ensaladas",
                            Especial = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3215),
                            Icono = "https://ik.imagekit.io/Mariocanizares/carne.webp?updatedAt=1726218723472",
                            NombreCategoria = "Ensaladas",
                            PuntuacionPromedio = 4.6m
                        },
                        new
                        {
                            IdCategoria = 8,
                            Descripcion = "Reconfortantes sopas y cremas",
                            Especial = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3218),
                            Icono = "https://ik.imagekit.io/Mariocanizares/sopa.png?updatedAt=1726218800718f",
                            NombreCategoria = "Sopas",
                            PuntuacionPromedio = 4.7m
                        },
                        new
                        {
                            IdCategoria = 9,
                            Descripcion = "Variedad de pizzas caseras",
                            Especial = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3221),
                            Icono = "https://ik.imagekit.io/Mariocanizares/pizza.png?updatedAt=1726218802077",
                            NombreCategoria = "Pizzas",
                            PuntuacionPromedio = 4.8m
                        },
                        new
                        {
                            IdCategoria = 10,
                            Descripcion = "Creativos y deliciosos sandwiches",
                            Especial = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3224),
                            Icono = "https://ik.imagekit.io/Mariocanizares/sandwitches.png?updatedAt=1726218800723",
                            NombreCategoria = "Sandwiches",
                            PuntuacionPromedio = 4.5m
                        },
                        new
                        {
                            IdCategoria = 11,
                            Descripcion = "Platos saludables de verduras",
                            Especial = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3229),
                            Icono = "https://ik.imagekit.io/Mariocanizares/verduras.png?updatedAt=1726218800742",
                            NombreCategoria = "Verduras",
                            PuntuacionPromedio = 4.6m
                        },
                        new
                        {
                            IdCategoria = 12,
                            Descripcion = "Salsas para acompañar tus platos",
                            Especial = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3232),
                            Icono = "https://ik.imagekit.io/Mariocanizares/salsas.png?updatedAt=1726218800564",
                            NombreCategoria = "Salsas",
                            PuntuacionPromedio = 4.7m
                        },
                        new
                        {
                            IdCategoria = 13,
                            Descripcion = "Dulces y sabrosos postres",
                            Especial = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3236),
                            Icono = "https://ik.imagekit.io/Mariocanizares/postres.png?updatedAt=1726218800753",
                            NombreCategoria = "Postres",
                            PuntuacionPromedio = 4.8m
                        },
                        new
                        {
                            IdCategoria = 14,
                            Descripcion = "Bebidas refrescantes y cócteles",
                            Especial = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3239),
                            Icono = "https://ik.imagekit.io/Mariocanizares/bebidas.png?updatedAt=1726218678224",
                            NombreCategoria = "Bebidas",
                            PuntuacionPromedio = 4.7m
                        },
                        new
                        {
                            IdCategoria = 15,
                            Descripcion = "Platos tradicionales de legumbres",
                            Especial = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3242),
                            Icono = "https://ik.imagekit.io/Mariocanizares/legumbres.png?updatedAt=1726218800787",
                            NombreCategoria = "Legumbres",
                            PuntuacionPromedio = 4.6m
                        });
                });

            modelBuilder.Entity("RecetasRedondas.Models.DiaMenu", b =>
                {
                    b.Property<int>("IdDiaMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiaMenu"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMenuSemanal")
                        .HasColumnType("int");

                    b.Property<int>("IdReceta")
                        .HasColumnType("int");

                    b.Property<bool>("TipoComida")
                        .HasColumnType("bit");

                    b.HasKey("IdDiaMenu");

                    b.HasIndex("IdMenuSemanal");

                    b.HasIndex("IdReceta");

                    b.ToTable("DiasMenu");
                });

            modelBuilder.Entity("RecetasRedondas.Models.Favorito", b =>
                {
                    b.Property<int>("IdFavorito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFavorito"));

                    b.Property<DateTime>("FechaFavorito")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdReceta")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdFavorito");

                    b.HasIndex("IdReceta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("RecetasRedondas.Models.Ingrediente", b =>
                {
                    b.Property<int>("IdIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIngrediente"));

                    b.Property<decimal>("Calorias")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ContieneAlergenos")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreIngrediente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAlergeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdIngrediente");

                    b.ToTable("Ingredientes");

                    b.HasData(
                        new
                        {
                            IdIngrediente = 1,
                            Calorias = 15m,
                            ContieneAlergenos = false,
                            FechaExpiracion = new DateTime(2024, 11, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(4007),
                            NombreIngrediente = "Lechuga",
                            TipoAlergeno = "",
                            UnidadMedida = "g"
                        },
                        new
                        {
                            IdIngrediente = 2,
                            Calorias = 130m,
                            ContieneAlergenos = false,
                            FechaExpiracion = new DateTime(2025, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(4021),
                            NombreIngrediente = "Arroz",
                            TipoAlergeno = "",
                            UnidadMedida = "g"
                        },
                        new
                        {
                            IdIngrediente = 3,
                            Calorias = 2m,
                            ContieneAlergenos = false,
                            FechaExpiracion = new DateTime(2025, 4, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(4025),
                            NombreIngrediente = "Café",
                            TipoAlergeno = "",
                            UnidadMedida = "ml"
                        });
                });

            modelBuilder.Entity("RecetasRedondas.Models.MenuSemanal", b =>
                {
                    b.Property<int>("IdMenuSemanal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMenuSemanal"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("NumSemana")
                        .HasColumnType("int");

                    b.HasKey("IdMenuSemanal");

                    b.HasIndex("IdUsuario");

                    b.ToTable("MenusSemanales");
                });

            modelBuilder.Entity("RecetasRedondas.Models.Paso", b =>
                {
                    b.Property<int>("IdPaso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaso"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdReceta")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("IdPaso");

                    b.HasIndex("IdReceta");

                    b.ToTable("Pasos");

                    b.HasData(
                        new
                        {
                            IdPaso = 1,
                            Descripcion = "Lavar y trocear la lechuga.",
                            IdReceta = 1,
                            ImagenUrl = "https://ik.imagekit.io/Mariocanizares/Recetas/ensalada.jpg?updatedAt=1727169325456",
                            Numero = 1
                        },
                        new
                        {
                            IdPaso = 2,
                            Descripcion = "Agregar el aderezo César y mezclar bien.",
                            IdReceta = 1,
                            ImagenUrl = "https://example.com/imagen2.jpg",
                            Numero = 2
                        },
                        new
                        {
                            IdPaso = 3,
                            Descripcion = "Servir y disfrutar.",
                            IdReceta = 1,
                            ImagenUrl = "https://example.com/imagen3.jpg",
                            Numero = 3
                        },
                        new
                        {
                            IdPaso = 4,
                            Descripcion = "Cocinar el arroz en caldo de pescado.",
                            IdReceta = 2,
                            ImagenUrl = "https://ik.imagekit.io/Mariocanizares/Recetas/arroz-marisco.jpg?updatedAt=1727169389258",
                            Numero = 1
                        },
                        new
                        {
                            IdPaso = 5,
                            Descripcion = "Agregar los mariscos y verduras.",
                            IdReceta = 2,
                            ImagenUrl = "https://example.com/imagen5.jpg",
                            Numero = 2
                        },
                        new
                        {
                            IdPaso = 6,
                            Descripcion = "Cocinar a fuego lento hasta que el arroz esté listo.",
                            IdReceta = 2,
                            ImagenUrl = "https://example.com/imagen6.jpg",
                            Numero = 3
                        },
                        new
                        {
                            IdPaso = 7,
                            Descripcion = "Preparar el café y dejar enfriar.",
                            IdReceta = 3,
                            ImagenUrl = "https://ik.imagekit.io/Mariocanizares/Recetas/tiramisu.jpg?updatedAt=1727169422091",
                            Numero = 1
                        },
                        new
                        {
                            IdPaso = 8,
                            Descripcion = "Mezclar el mascarpone con azúcar.",
                            IdReceta = 3,
                            ImagenUrl = "https://example.com/imagen8.jpg",
                            Numero = 2
                        },
                        new
                        {
                            IdPaso = 9,
                            Descripcion = "Montar los ingredientes en capas.",
                            IdReceta = 3,
                            ImagenUrl = "https://example.com/imagen9.jpg",
                            Numero = 3
                        });
                });

            modelBuilder.Entity("RecetasRedondas.Models.Receta", b =>
                {
                    b.Property<int>("IdReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReceta"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsVegano")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NivelDificultad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TiempoPreparacion")
                        .HasColumnType("int");

                    b.HasKey("IdReceta");

                    b.ToTable("Recetas");

                    b.HasData(
                        new
                        {
                            IdReceta = 1,
                            Descripcion = "Ensalada fresca con aderezo César",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3713),
                            IdCategoria = 1,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/ensalada.jpg?updatedAt=1727169325456",
                            NivelDificultad = 1m,
                            Nombre = "Ensalada César",
                            TiempoPreparacion = 20
                        },
                        new
                        {
                            IdReceta = 2,
                            Descripcion = "Arroz tradicional español con mariscos",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3728),
                            IdCategoria = 2,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/arroz-marisco.jpg?updatedAt=1727169389258",
                            NivelDificultad = 2m,
                            Nombre = "Paella",
                            TiempoPreparacion = 60
                        },
                        new
                        {
                            IdReceta = 3,
                            Descripcion = "Postre italiano con café y mascarpone",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3733),
                            IdCategoria = 3,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/tiramisu.jpg?updatedAt=1727169422091",
                            NivelDificultad = 3m,
                            Nombre = "Tiramisú",
                            TiempoPreparacion = 30
                        },
                        new
                        {
                            IdReceta = 4,
                            Descripcion = "Pasta con salsa cremosa de huevo y panceta",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3736),
                            IdCategoria = 4,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/carbonara.jpg?updatedAt=1727169452310",
                            NivelDificultad = 2m,
                            Nombre = "Pasta Carbonara",
                            TiempoPreparacion = 25
                        },
                        new
                        {
                            IdReceta = 5,
                            Descripcion = "Rollos de arroz y pescado crudo",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3740),
                            IdCategoria = 5,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/sushi.jpg?updatedAt=1727169470676",
                            NivelDificultad = 3m,
                            Nombre = "Sushi",
                            TiempoPreparacion = 50
                        },
                        new
                        {
                            IdReceta = 6,
                            Descripcion = "Pizza clásica con tomate, mozzarella y albahaca",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3744),
                            IdCategoria = 6,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/pizza.jpg?updatedAt=1727169491728",
                            NivelDificultad = 2m,
                            Nombre = "Pizza Margherita",
                            TiempoPreparacion = 40
                        },
                        new
                        {
                            IdReceta = 7,
                            Descripcion = "Aguacate triturado con cebolla, tomate y limón",
                            EsVegano = true,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3749),
                            IdCategoria = 1,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/guacamole.jpg?updatedAt=1727169511551",
                            NivelDificultad = 1m,
                            Nombre = "Guacamole",
                            TiempoPreparacion = 10
                        },
                        new
                        {
                            IdReceta = 8,
                            Descripcion = "Capas de pasta, carne y salsa de tomate",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3753),
                            IdCategoria = 4,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/lasagna.jpg?updatedAt=1727169528673",
                            NivelDificultad = 3m,
                            Nombre = "Lasaña",
                            TiempoPreparacion = 90
                        },
                        new
                        {
                            IdReceta = 9,
                            Descripcion = "Tacos rellenos de pollo, cebolla y cilantro",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3756),
                            IdCategoria = 2,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/tacos.jpg?updatedAt=1727169541523",
                            NivelDificultad = 2m,
                            Nombre = "Tacos de Pollo",
                            TiempoPreparacion = 30
                        },
                        new
                        {
                            IdReceta = 10,
                            Descripcion = "Deliciosos brownies de chocolate",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3759),
                            IdCategoria = 3,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/brownies.jpg?updatedAt=1727169556237",
                            NivelDificultad = 2m,
                            Nombre = "Brownies",
                            TiempoPreparacion = 45
                        },
                        new
                        {
                            IdReceta = 11,
                            Descripcion = "Sopa nutritiva de lentejas",
                            EsVegano = true,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3763),
                            IdCategoria = 1,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/lentejas.jpg?updatedAt=1727169570913",
                            NivelDificultad = 1m,
                            Nombre = "Sopa de Lentejas",
                            TiempoPreparacion = 35
                        },
                        new
                        {
                            IdReceta = 12,
                            Descripcion = "Guiso picante de carne y frijoles",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3768),
                            IdCategoria = 2,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/chili.jpg?updatedAt=1727169584071",
                            NivelDificultad = 3m,
                            Nombre = "Chili con Carne",
                            TiempoPreparacion = 50
                        },
                        new
                        {
                            IdReceta = 13,
                            Descripcion = "Dip de berenjena asada",
                            EsVegano = true,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3771),
                            IdCategoria = 1,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/baba-ganoush.jpg?updatedAt=1727169596850",
                            NivelDificultad = 2m,
                            Nombre = "Baba Ganoush",
                            TiempoPreparacion = 20
                        },
                        new
                        {
                            IdReceta = 14,
                            Descripcion = "Deliciosos crepes dulces o salados",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3777),
                            IdCategoria = 3,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/crepes.jpg?updatedAt=1727169607858",
                            NivelDificultad = 2m,
                            Nombre = "Crepes",
                            TiempoPreparacion = 30
                        },
                        new
                        {
                            IdReceta = 15,
                            Descripcion = "Pollo cocido en salsa de curry",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3781),
                            IdCategoria = 2,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/pollo-curry.jpg?updatedAt=1727169619493",
                            NivelDificultad = 3m,
                            Nombre = "Pollo al Curry",
                            TiempoPreparacion = 40
                        },
                        new
                        {
                            IdReceta = 16,
                            Descripcion = "Galletas crujientes de chocolate",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3784),
                            IdCategoria = 3,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/galletas-chocolate.jpg?updatedAt=1727169630571",
                            NivelDificultad = 1m,
                            Nombre = "Galletas de Chocolate",
                            TiempoPreparacion = 25
                        },
                        new
                        {
                            IdReceta = 17,
                            Descripcion = "Tarta salada con verduras y queso",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3846),
                            IdCategoria = 4,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/quiche.jpg?updatedAt=1727169642129",
                            NivelDificultad = 3m,
                            Nombre = "Quiche de Verduras",
                            TiempoPreparacion = 50
                        },
                        new
                        {
                            IdReceta = 18,
                            Descripcion = "Muffins esponjosos con arándanos",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3852),
                            IdCategoria = 3,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/muffins.jpg?updatedAt=1727169653441",
                            NivelDificultad = 2m,
                            Nombre = "Muffins de Arándano",
                            TiempoPreparacion = 35
                        },
                        new
                        {
                            IdReceta = 19,
                            Descripcion = "Batido saludable de espinacas y plátano",
                            EsVegano = true,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3857),
                            IdCategoria = 1,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/batido-verde.jpg?updatedAt=1727169666491",
                            NivelDificultad = 1m,
                            Nombre = "Batido Verde",
                            TiempoPreparacion = 15
                        },
                        new
                        {
                            IdReceta = 20,
                            Descripcion = "Salmón asado con hierbas",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3862),
                            IdCategoria = 2,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/salmon.jpg?updatedAt=1727169677362",
                            NivelDificultad = 2m,
                            Nombre = "Salmón al Horno",
                            TiempoPreparacion = 30
                        },
                        new
                        {
                            IdReceta = 21,
                            Descripcion = "Pancakes esponjosos con jarabe de arce",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3865),
                            IdCategoria = 3,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/pancakes.jpg?updatedAt=1727169687612",
                            NivelDificultad = 1m,
                            Nombre = "Pancakes",
                            TiempoPreparacion = 20
                        },
                        new
                        {
                            IdReceta = 22,
                            Descripcion = "Sopa fría de tomate",
                            EsVegano = true,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3869),
                            IdCategoria = 1,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/gazpacho.jpg?updatedAt=1727169697098",
                            NivelDificultad = 2m,
                            Nombre = "Gazpacho",
                            TiempoPreparacion = 15
                        },
                        new
                        {
                            IdReceta = 23,
                            Descripcion = "Bolas fritas rellenas de bechamel",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3872),
                            IdCategoria = 4,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/croquetas.jpg?updatedAt=1727169707360",
                            NivelDificultad = 3m,
                            Nombre = "Croquetas",
                            TiempoPreparacion = 45
                        },
                        new
                        {
                            IdReceta = 24,
                            Descripcion = "Pudín saludable con semillas de chía",
                            EsVegano = true,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3877),
                            IdCategoria = 3,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/pudin-chia.jpg?updatedAt=1727169717454",
                            NivelDificultad = 1m,
                            Nombre = "Pudín de Chía",
                            TiempoPreparacion = 15
                        },
                        new
                        {
                            IdReceta = 25,
                            Descripcion = "Pescado marinado en jugo de limón",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3881),
                            IdCategoria = 2,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/ceviche.jpg?updatedAt=1727169726708",
                            NivelDificultad = 3m,
                            Nombre = "Ceviche",
                            TiempoPreparacion = 30
                        },
                        new
                        {
                            IdReceta = 26,
                            Descripcion = "Huevos con salsa de tomate y frijoles",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3885),
                            IdCategoria = 4,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/huevos-rancheros.jpg?updatedAt=1727169737304",
                            NivelDificultad = 2m,
                            Nombre = "Huevos Rancheros",
                            TiempoPreparacion = 25
                        },
                        new
                        {
                            IdReceta = 27,
                            Descripcion = "Pimientos rellenos de carne y arroz",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3888),
                            IdCategoria = 4,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/pimientos-rellenos.jpg?updatedAt=1727169746992",
                            NivelDificultad = 3m,
                            Nombre = "Pimientos Rellenos",
                            TiempoPreparacion = 50
                        },
                        new
                        {
                            IdReceta = 28,
                            Descripcion = "Zanahorias asadas con miel y especias",
                            EsVegano = true,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3891),
                            IdCategoria = 1,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/zanahorias.jpg?updatedAt=1727169756553",
                            NivelDificultad = 1m,
                            Nombre = "Zanahorias Asadas",
                            TiempoPreparacion = 30
                        },
                        new
                        {
                            IdReceta = 29,
                            Descripcion = "Pasta con salsa pesto fresca",
                            EsVegano = true,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3897),
                            IdCategoria = 4,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/pasta-pesto.jpg?updatedAt=1727169765990",
                            NivelDificultad = 2m,
                            Nombre = "Pasta al Pesto",
                            TiempoPreparacion = 20
                        },
                        new
                        {
                            IdReceta = 30,
                            Descripcion = "Batido refrescante de fresa",
                            EsVegano = true,
                            FechaCreacion = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(3902),
                            IdCategoria = 1,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/batido-fresa.jpg?updatedAt=1727169775184",
                            NivelDificultad = 1m,
                            Nombre = "Batido de Fresa",
                            TiempoPreparacion = 10
                        });
                });

            modelBuilder.Entity("RecetasRedondas.Models.RecetaIngrediente", b =>
                {
                    b.Property<int>("IdRecetaIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecetaIngrediente"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EsOpcional")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAñadido")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdIngrediente")
                        .HasColumnType("int");

                    b.Property<int>("IdReceta")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRecetaIngrediente");

                    b.HasIndex("IdIngrediente");

                    b.HasIndex("IdReceta");

                    b.ToTable("RecetaIngredientes");

                    b.HasData(
                        new
                        {
                            IdRecetaIngrediente = 1,
                            Cantidad = 100m,
                            EsOpcional = false,
                            FechaAñadido = new DateTime(2024, 11, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(4063),
                            IdIngrediente = 1,
                            IdReceta = 1,
                            Notas = ""
                        },
                        new
                        {
                            IdRecetaIngrediente = 2,
                            Cantidad = 200m,
                            EsOpcional = false,
                            FechaAñadido = new DateTime(2024, 11, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(4071),
                            IdIngrediente = 2,
                            IdReceta = 2,
                            Notas = ""
                        },
                        new
                        {
                            IdRecetaIngrediente = 3,
                            Cantidad = 50m,
                            EsOpcional = false,
                            FechaAñadido = new DateTime(2024, 11, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(4075),
                            IdIngrediente = 3,
                            IdReceta = 3,
                            Notas = ""
                        });
                });

            modelBuilder.Entity("RecetasRedondas.Models.RecetasPaso", b =>
                {
                    b.Property<int>("IdReceta")
                        .HasColumnType("int");

                    b.Property<int>("IdPaso")
                        .HasColumnType("int");

                    b.Property<int>("IdRecetasPaso")
                        .HasColumnType("int");

                    b.HasKey("IdReceta", "IdPaso");

                    b.HasIndex("IdPaso");

                    b.ToTable("recetasPasos");
                });

            modelBuilder.Entity("RecetasRedondas.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rol")
                        .HasColumnType("bit");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Contrasena = "MarioX8",
                            Correo = "mario@gmail.com",
                            FechaRegistro = new DateTime(2024, 10, 21, 12, 43, 47, 94, DateTimeKind.Local).AddTicks(4112),
                            Nombre = "Admin",
                            Rol = true
                        });
                });

            modelBuilder.Entity("RecetasRedondas.Models.Alergeno", b =>
                {
                    b.HasOne("RecetasRedondas.Models.Ingrediente", "Ingredientes")
                        .WithMany()
                        .HasForeignKey("IngredientesIdIngrediente");

                    b.HasOne("RecetasRedondas.Models.Usuario", "Usuarios")
                        .WithMany("Alergenos")
                        .HasForeignKey("UsuariosIdUsuario");

                    b.Navigation("Ingredientes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("RecetasRedondas.Models.DiaMenu", b =>
                {
                    b.HasOne("RecetasRedondas.Models.MenuSemanal", "MenuSemanal")
                        .WithMany("DiasMenu")
                        .HasForeignKey("IdMenuSemanal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecetasRedondas.Models.Receta", "Receta")
                        .WithMany()
                        .HasForeignKey("IdReceta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuSemanal");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("RecetasRedondas.Models.Favorito", b =>
                {
                    b.HasOne("RecetasRedondas.Models.Receta", "Receta")
                        .WithMany()
                        .HasForeignKey("IdReceta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecetasRedondas.Models.Usuario", "Usuario")
                        .WithMany("Favoritos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RecetasRedondas.Models.MenuSemanal", b =>
                {
                    b.HasOne("RecetasRedondas.Models.Usuario", "Usuario")
                        .WithMany("MenusSemanales")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RecetasRedondas.Models.Paso", b =>
                {
                    b.HasOne("RecetasRedondas.Models.Receta", "Receta")
                        .WithMany("Pasos")
                        .HasForeignKey("IdReceta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("RecetasRedondas.Models.RecetaIngrediente", b =>
                {
                    b.HasOne("RecetasRedondas.Models.Ingrediente", "Ingrediente")
                        .WithMany("recetaIngredientes")
                        .HasForeignKey("IdIngrediente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecetasRedondas.Models.Receta", "Receta")
                        .WithMany("recetaIngredientes")
                        .HasForeignKey("IdReceta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("RecetasRedondas.Models.RecetasPaso", b =>
                {
                    b.HasOne("RecetasRedondas.Models.Paso", "Paso")
                        .WithMany()
                        .HasForeignKey("IdPaso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecetasRedondas.Models.Receta", "Receta")
                        .WithMany()
                        .HasForeignKey("IdReceta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paso");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("RecetasRedondas.Models.Ingrediente", b =>
                {
                    b.Navigation("recetaIngredientes");
                });

            modelBuilder.Entity("RecetasRedondas.Models.MenuSemanal", b =>
                {
                    b.Navigation("DiasMenu");
                });

            modelBuilder.Entity("RecetasRedondas.Models.Receta", b =>
                {
                    b.Navigation("Pasos");

                    b.Navigation("recetaIngredientes");
                });

            modelBuilder.Entity("RecetasRedondas.Models.Usuario", b =>
                {
                    b.Navigation("Alergenos");

                    b.Navigation("Favoritos");

                    b.Navigation("MenusSemanales");
                });
#pragma warning restore 612, 618
        }
    }
}
