// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecetasRedondas.Models;

#nullable disable

namespace RecetasRedondas.Data.Migrations
{
    [DbContext(typeof(RecetasRedondasAppContext))]
    partial class RecetasRedondasAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecetasRedondas.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PuntuacionPromedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Descripcion = "Platos deliciosos de carne",
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(2505),
                            Icono = "https://ik.imagekit.io/Mariocanizares/carne.webp?updatedAt=1726218723472",
                            NombreCategoria = "Carnes",
                            PuntuacionPromedio = 4.5m,
                            Visible = true
                        },
                        new
                        {
                            IdCategoria = 2,
                            Descripcion = "Platos variados con arroz",
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(2596),
                            Icono = "https://ik.imagekit.io/Mariocanizares/arroz.png?updatedAt=1726218452623",
                            NombreCategoria = "Arroces",
                            PuntuacionPromedio = 4.8m,
                            Visible = true
                        },
                        new
                        {
                            IdCategoria = 3,
                            Descripcion = "Guisos tradicionales y caseros",
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(2605),
                            Icono = "https://ik.imagekit.io/Mariocanizares/guisos.png?updatedAt=1726218800757",
                            NombreCategoria = "Guisos",
                            PuntuacionPromedio = 4.7m,
                            Visible = true
                        },
                        new
                        {
                            IdCategoria = 4,
                            Descripcion = "Platos exquisitos de mariscos",
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(2611),
                            Icono = "https://ik.imagekit.io/Mariocanizares/marisco.webp?updatedAt=1726218800789",
                            NombreCategoria = "Mariscos",
                            PuntuacionPromedio = 4.6m,
                            Visible = true
                        },
                        new
                        {
                            IdCategoria = 5,
                            Descripcion = "Platos frescos de pescados",
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(2617),
                            Icono = "https://ik.imagekit.io/Mariocanizares/pescado.png?updatedAt=1726218801946",
                            NombreCategoria = "Pescados",
                            PuntuacionPromedio = 4.7m,
                            Visible = true
                        },
                        new
                        {
                            IdCategoria = 6,
                            Descripcion = "Platos deliciosos de pasta",
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(2622),
                            Icono = "https://ik.imagekit.io/Mariocanizares/pasta.png?updatedAt=1726218800772",
                            NombreCategoria = "Pastas",
                            PuntuacionPromedio = 4.5m,
                            Visible = true
                        },
                        new
                        {
                            IdCategoria = 7,
                            Descripcion = "Frescas y saludables ensaladas",
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(2628),
                            Icono = "https://ik.imagekit.io/Mariocanizares/carne.webp?updatedAt=1726218723472",
                            NombreCategoria = "Ensaladas",
                            PuntuacionPromedio = 4.6m,
                            Visible = true
                        },
                        new
                        {
                            IdCategoria = 8,
                            Descripcion = "Reconfortantes sopas y cremas",
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(2633),
                            Icono = "https://ik.imagekit.io/Mariocanizares/sopa.png?updatedAt=1726218800718f",
                            NombreCategoria = "Sopas",
                            PuntuacionPromedio = 4.7m,
                            Visible = true
                        },
                        new
                        {
                            IdCategoria = 9,
                            Descripcion = "Variedad de pizzas caseras",
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(2642),
                            Icono = "https://ik.imagekit.io/Mariocanizares/pizza.png?updatedAt=1726218802077",
                            NombreCategoria = "Pizzas",
                            PuntuacionPromedio = 4.8m,
                            Visible = true
                        },
                        new
                        {
                            IdCategoria = 10,
                            Descripcion = "Creativos y deliciosos sandwiches",
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(2670),
                            Icono = "https://ik.imagekit.io/Mariocanizares/sandwitches.png?updatedAt=1726218800723",
                            NombreCategoria = "Sandwiches",
                            PuntuacionPromedio = 4.5m,
                            Visible = true
                        },
                        new
                        {
                            IdCategoria = 11,
                            Descripcion = "Platos saludables de verduras",
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(2682),
                            Icono = "https://ik.imagekit.io/Mariocanizares/verduras.png?updatedAt=1726218800742",
                            NombreCategoria = "Verduras",
                            PuntuacionPromedio = 4.6m,
                            Visible = true
                        },
                        new
                        {
                            IdCategoria = 12,
                            Descripcion = "Salsas para acompañar tus platos",
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(2689),
                            Icono = "https://ik.imagekit.io/Mariocanizares/salsas.png?updatedAt=1726218800564",
                            NombreCategoria = "Salsas",
                            PuntuacionPromedio = 4.7m,
                            Visible = true
                        },
                        new
                        {
                            IdCategoria = 13,
                            Descripcion = "Dulces y sabrosos postres",
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(2695),
                            Icono = "https://ik.imagekit.io/Mariocanizares/postres.png?updatedAt=1726218800753",
                            NombreCategoria = "Postres",
                            PuntuacionPromedio = 4.8m,
                            Visible = true
                        },
                        new
                        {
                            IdCategoria = 14,
                            Descripcion = "Bebidas refrescantes y cócteles",
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(2701),
                            Icono = "https://ik.imagekit.io/Mariocanizares/bebidas.png?updatedAt=1726218678224",
                            NombreCategoria = "Bebidas",
                            PuntuacionPromedio = 4.7m,
                            Visible = true
                        },
                        new
                        {
                            IdCategoria = 15,
                            Descripcion = "Platos tradicionales de legumbres",
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(2706),
                            Icono = "https://ik.imagekit.io/Mariocanizares/legumbres.png?updatedAt=1726218800787",
                            NombreCategoria = "Legumbres",
                            PuntuacionPromedio = 4.6m,
                            Visible = true
                        });
                });

            modelBuilder.Entity("RecetasRedondas.Models.Ingrediente", b =>
                {
                    b.Property<int>("IdIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIngrediente"));

                    b.Property<decimal>("Calorias")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ContieneAlergenos")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreIngrediente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAlergeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdIngrediente");

                    b.ToTable("Ingredientes");

                    b.HasData(
                        new
                        {
                            IdIngrediente = 1,
                            Calorias = 15m,
                            ContieneAlergenos = false,
                            FechaExpiracion = new DateTime(2024, 10, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(5840),
                            NombreIngrediente = "Lechuga",
                            TipoAlergeno = "",
                            UnidadMedida = "g"
                        },
                        new
                        {
                            IdIngrediente = 2,
                            Calorias = 130m,
                            ContieneAlergenos = false,
                            FechaExpiracion = new DateTime(2025, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(5870),
                            NombreIngrediente = "Arroz",
                            TipoAlergeno = "",
                            UnidadMedida = "g"
                        },
                        new
                        {
                            IdIngrediente = 3,
                            Calorias = 2m,
                            ContieneAlergenos = false,
                            FechaExpiracion = new DateTime(2025, 3, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(5888),
                            NombreIngrediente = "Café",
                            TipoAlergeno = "",
                            UnidadMedida = "ml"
                        });
                });

            modelBuilder.Entity("RecetasRedondas.Models.MenuSemanal", b =>
                {
                    b.Property<int>("IdMenuSemanal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMenuSemanal"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdMenuSemanal");

                    b.ToTable("MenusSemanales");

                    b.HasData(
                        new
                        {
                            IdMenuSemanal = 1,
                            Descripcion = "Menú semanal de prueba",
                            FechaFin = new DateTime(2024, 10, 4, 10, 37, 17, 322, DateTimeKind.Local).AddTicks(2418),
                            FechaInicio = new DateTime(2024, 9, 27, 10, 37, 17, 322, DateTimeKind.Local).AddTicks(2407),
                            IdUsuario = 1
                        });
                });

            modelBuilder.Entity("RecetasRedondas.Models.MenuSemanalReceta", b =>
                {
                    b.Property<int>("IdMenuSemanal")
                        .HasColumnType("int");

                    b.Property<int>("IdReceta")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("IdMenuSemanal", "IdReceta", "Fecha");

                    b.ToTable("MenuSemanalRecetas");

                    b.HasData(
                        new
                        {
                            IdMenuSemanal = 1,
                            IdReceta = 1,
                            Fecha = new DateTime(2024, 9, 27, 10, 37, 17, 322, DateTimeKind.Local).AddTicks(2474)
                        },
                        new
                        {
                            IdMenuSemanal = 1,
                            IdReceta = 2,
                            Fecha = new DateTime(2024, 9, 28, 10, 37, 17, 322, DateTimeKind.Local).AddTicks(2482)
                        },
                        new
                        {
                            IdMenuSemanal = 1,
                            IdReceta = 3,
                            Fecha = new DateTime(2024, 9, 29, 10, 37, 17, 322, DateTimeKind.Local).AddTicks(2487)
                        });
                });

            modelBuilder.Entity("RecetasRedondas.Models.Paso", b =>
                {
                    b.Property<int>("IdPaso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaso"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdReceta")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("IdPaso");

                    b.HasIndex("IdReceta");

                    b.ToTable("Pasos");

                    b.HasData(
                        new
                        {
                            IdPaso = 1,
                            Descripcion = "Lavar y trocear la lechuga.",
                            IdReceta = 1,
                            ImagenUrl = "https://ik.imagekit.io/Mariocanizares/Recetas/ensalada.jpg?updatedAt=1727169325456",
                            Numero = 1
                        },
                        new
                        {
                            IdPaso = 2,
                            Descripcion = "Agregar el aderezo César y mezclar bien.",
                            IdReceta = 1,
                            ImagenUrl = "https://example.com/imagen2.jpg",
                            Numero = 2
                        },
                        new
                        {
                            IdPaso = 3,
                            Descripcion = "Servir y disfrutar.",
                            IdReceta = 1,
                            ImagenUrl = "https://example.com/imagen3.jpg",
                            Numero = 3
                        },
                        new
                        {
                            IdPaso = 4,
                            Descripcion = "Cocinar el arroz en caldo de pescado.",
                            IdReceta = 2,
                            ImagenUrl = "https://ik.imagekit.io/Mariocanizares/Recetas/arroz-marisco.jpg?updatedAt=1727169389258",
                            Numero = 1
                        },
                        new
                        {
                            IdPaso = 5,
                            Descripcion = "Agregar los mariscos y verduras.",
                            IdReceta = 2,
                            ImagenUrl = "https://example.com/imagen5.jpg",
                            Numero = 2
                        },
                        new
                        {
                            IdPaso = 6,
                            Descripcion = "Cocinar a fuego lento hasta que el arroz esté listo.",
                            IdReceta = 2,
                            ImagenUrl = "https://example.com/imagen6.jpg",
                            Numero = 3
                        },
                        new
                        {
                            IdPaso = 7,
                            Descripcion = "Preparar el café y dejar enfriar.",
                            IdReceta = 3,
                            ImagenUrl = "https://ik.imagekit.io/Mariocanizares/Recetas/tiramisu.jpg?updatedAt=1727169422091",
                            Numero = 1
                        },
                        new
                        {
                            IdPaso = 8,
                            Descripcion = "Mezclar el mascarpone con azúcar.",
                            IdReceta = 3,
                            ImagenUrl = "https://example.com/imagen8.jpg",
                            Numero = 2
                        },
                        new
                        {
                            IdPaso = 9,
                            Descripcion = "Montar los ingredientes en capas.",
                            IdReceta = 3,
                            ImagenUrl = "https://example.com/imagen9.jpg",
                            Numero = 3
                        });
                });

            modelBuilder.Entity("RecetasRedondas.Models.Receta", b =>
                {
                    b.Property<int>("IdReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReceta"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsVegano")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NivelDificultad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TiempoPreparacion")
                        .HasColumnType("int");

                    b.HasKey("IdReceta");

                    b.ToTable("Recetas");

                    b.HasData(
                        new
                        {
                            IdReceta = 1,
                            Descripcion = "Ensalada fresca con aderezo César",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(5521),
                            IdCategoria = 1,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/ensalada.jpg?updatedAt=1727169325456",
                            NivelDificultad = 1m,
                            Nombre = "Ensalada César",
                            TiempoPreparacion = 20
                        },
                        new
                        {
                            IdReceta = 2,
                            Descripcion = "Arroz tradicional español con mariscos",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(5566),
                            IdCategoria = 2,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/arroz-marisco.jpg?updatedAt=1727169389258",
                            NivelDificultad = 2m,
                            Nombre = "Paella",
                            TiempoPreparacion = 60
                        },
                        new
                        {
                            IdReceta = 3,
                            Descripcion = "Postre italiano con café y mascarpone",
                            EsVegano = false,
                            FechaCreacion = new DateTime(2024, 9, 27, 10, 37, 17, 321, DateTimeKind.Local).AddTicks(5587),
                            IdCategoria = 3,
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Recetas/tiramisu.jpg?updatedAt=1727169422091",
                            NivelDificultad = 3m,
                            Nombre = "Tiramisú",
                            TiempoPreparacion = 30
                        });
                });

            modelBuilder.Entity("RecetasRedondas.Models.RecetaIngrediente", b =>
                {
                    b.Property<int>("IdReceta")
                        .HasColumnType("int");

                    b.Property<int>("IdIngrediente")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EsOpcional")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAñadido")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdReceta", "IdIngrediente");

                    b.HasIndex("IdIngrediente");

                    b.ToTable("RecetaIngredientes");

                    b.HasData(
                        new
                        {
                            IdReceta = 1,
                            IdIngrediente = 1,
                            Cantidad = 100m,
                            EsOpcional = false,
                            FechaAñadido = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notas = ""
                        },
                        new
                        {
                            IdReceta = 2,
                            IdIngrediente = 2,
                            Cantidad = 200m,
                            EsOpcional = false,
                            FechaAñadido = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notas = ""
                        },
                        new
                        {
                            IdReceta = 3,
                            IdIngrediente = 3,
                            Cantidad = 50m,
                            EsOpcional = false,
                            FechaAñadido = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notas = ""
                        });
                });

            modelBuilder.Entity("RecetasRedondas.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rol")
                        .HasColumnType("bit");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Contrasena = "MarioX8",
                            Correo = "mario@gmail.com",
                            FechaRegistro = new DateTime(2024, 9, 27, 10, 37, 17, 322, DateTimeKind.Local).AddTicks(2232),
                            Nombre = "Admin",
                            Rol = true
                        });
                });

            modelBuilder.Entity("RecetasRedondas.Models.Paso", b =>
                {
                    b.HasOne("RecetasRedondas.Models.Receta", "Receta")
                        .WithMany("Pasos")
                        .HasForeignKey("IdReceta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("RecetasRedondas.Models.RecetaIngrediente", b =>
                {
                    b.HasOne("RecetasRedondas.Models.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("IdIngrediente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecetasRedondas.Models.Receta", null)
                        .WithMany()
                        .HasForeignKey("IdReceta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecetasRedondas.Models.Receta", b =>
                {
                    b.Navigation("Pasos");
                });
#pragma warning restore 612, 618
        }
    }
}
